site_name: Iroh Coin

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.expand
    - content.code.copy
    - content.action.view
    - content.tabs.link
    - toc.follow
    - navigation.top
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - offline
  - search
  - macros:
      on_error_fail: true
      on_undefined: strict

extra:
  iroh_token_address: "0x0fCEa0D43d8D125fD23D8c6EE048187058D9fe48"
  usdc_token_address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"

edit_uri: https://github.com/chinmaygarde/irohcoin/edit/main/docs/

repo_url: https://github.com/chinmaygarde/irohcoin
repo_name: chinmaygarde/irohcoin

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
      title: On this page
