[project]
name = "irohcoin"
version = "0.1.0"
description = "Iroh Coin"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-macros-plugin>=1.3.9",
    "mkdocs-material>=9.6.17",
]
